#!/usr/bin/env ruby
#Source generated by dia2code.



# core - short description
# Author:: <authors@email.com>
# Copyright:: (C) XXX
# License:: GPL
# Drupal core

class Core

  # XXX 
  # * access public
  attr_acessor :version
  public :version

  # XXX
  # * access public 
  def upgrade
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :upgrade

  # XXX
  # * access public 
  def downgrade
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :downgrade

  # XXX
  # * access private 
  def download
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  private :download

  # XXX
  # * access private 
  def unpack
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  private :unpack

end



