#!/usr/bin/env ruby
#Source generated by dia2code.



# database - short description
# Author:: <authors@email.com>
# Copyright:: (C) XXX
# License:: GPL
# XXX

class Database

  # XXX 
  # * access public
  attr_acessor :name
  public :name

  # XXX 
  # * access public
  attr_acessor :user
  public :user

  # XXX 
  # * access public
  attr_acessor :pass
  public :pass

  # XXX 
  # * access public
  attr_acessor :host
  public :host

  # XXX
  # * access public 
  def connect
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :connect

  # XXX
  # * access public 
  def disconnect
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :disconnect

end



