#!/usr/bin/env ruby
#Source generated by dia2code.



# module - short description
# Author:: <authors@email.com>
# Copyright:: (C) XXX
# License:: GPL
# XXX

class Module

  # XXX 
  # * access public
  attr_acessor :namespace
  public :namespace

  # XXX 
  # * access public
  attr_acessor :name
  public :name

  # XXX 
  # * access public
  attr_acessor :description
  public :description

  # XXX 
  # * access public
  attr_acessor :version
  public :version

  # XXX
  # * access public 
  def enable
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :enable

  # XXX
  # * access public 
  def disable
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :disable

  # XXX
  # * access public 
  def install
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :install

  # remove or delete entirely
  # * access public 
  def uninstall
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :uninstall

  # XXX
  # * access public 
  def upgrade
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :upgrade

  # XXX
  # * access public 
  def downgrade
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :downgrade

end



