#!/usr/bin/env ruby
#Source generated by dia2code.



# project - short description
# Author:: <authors@email.com>
# Copyright:: (C) XXX
# License:: GPL
# XXX

class Project

  # auto increment 
  # * access public
  attr_acessor :id
  public :id

  # XXX 
  # * access public
  attr_acessor :project_code
  public :project_code

  # XXX 
  # * access public
  attr_acessor :location
  public :location

  # Human readable name 
  # * access public
  attr_acessor :name
  public :name

  # XXX 
  # * access public
  attr_acessor :github
  public :github

  # XXX
  # * access public 
  # * param  code 
  # * param  name 
  # * param  location 
  def create( code, name, location )
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :create

  # XXX
  # * access public 
  # * param  code 
  def delete( code )
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :delete

  # XXX
  # * access public 
  # * param enum environment 
  def stage( environment )
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :stage

end



