#!/usr/bin/env ruby
#Source generated by dia2code.



# site - short description
# Author:: <authors@email.com>
# Copyright:: (C) XXX
# License:: GPL
# XXX

class Site

  # XXX 
  # * access public
  attr_acessor :url
  public :url

  # XXX 
  # * access public
  attr_acessor :database
  public :database

  # list of available modules in this site 
  # * access protected
  attr :modules-available
  protected :modules-available

  # XXX
  # * access public 
  def set_offline
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :set_offline

  # XXX
  # * access public 
  def set_online
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :set_online

  # XXX
  # * access public 
  def set_variable
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :set_variable

  # XXX
  # * access public 
  def get_gariable
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :get_gariable

  # XXX
  # * access public 
  def del_variable
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :del_variable

  # XXX
  # * access public 
  def upgrade
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :upgrade

  # XXX
  # * access public 
  def downgrade
    raise NotImplementedError, 'This is auto-gen. method, please implement.'
  end
  public :downgrade

end



